#!/usr/bin/env python3
"""
plot_coins.py — Per-coin (BTC vs ETH) breakdown charts from a single isolated run.

Reproduces the 7 per-coin charts that were previously generated by an internal
(uncommitted) script:

  08b_coin_A_liq_rates.png     — Paper vs HL liquidation rate, grouped bars
  08b_coin_B_winrate.png       — win rate by direction (Long/Short), grouped bars
  08b_coin_C_ev_dist.png       — EV-per-trade distribution (trader perspective)
  08b_coin_D_adverse_moves.png — worst-adverse-move distribution + bust threshold
  08b_coin_E_lp_delta.png      — LP-delta-per-trade distribution
  08b_coin_F_summary.png       — BTC vs ETH summary table
  08c_liq_by_coin.png          — daily Paper liquidation rate per coin (time series)

Reads paper_sim_trades.parquet from --sim-dir (default sim_flow_1.00) and the
liquidation threshold from --config. Writes PNGs into --charts-dir (default charts/).

Usage:
    python3 plot_coins.py
    python3 plot_coins.py --sim-dir sim_flow_1.00 --config paper_config.yaml --charts-dir charts
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker
import numpy as np
import pandas as pd
import yaml

# BTC / ETH colours (approx. match the original charts)
COL = {"BTC": "#f0a04b", "ETH": "#8390e8"}
COL_LONG = "#4caf50"
COL_SHORT = "#e0554b"
COINS = ["BTC", "ETH"]
DAY_MS = 86_400_000

# HL max-leverage tier per coin (annotation only)
MAX_LEV = {"BTC": 40, "ETH": 25}


def signed_log10(x: np.ndarray) -> np.ndarray:
    """Signed log compression: sign(x) * log10(|x| + 1)."""
    return np.sign(x) * np.log10(np.abs(x) + 1.0)


def _save(fig, out: Path, name: str):
    path = out / name
    fig.savefig(path, bbox_inches="tight", dpi=130)
    plt.close(fig)
    logging.info("  %s", name)


def load(sim_dir: Path, cfg: dict) -> tuple[pd.DataFrame, float]:
    trades = pd.read_parquet(sim_dir / "paper_sim_trades.parquet")
    # some price/pnl columns arrive as decimal.Decimal — coerce to float
    for col in ("open_px", "close_px", "worst_adverse_px",
                "user_pnl_usd", "lp_balance_delta_usd"):
        if col in trades.columns:
            trades[col] = pd.to_numeric(trades[col], errors="coerce").astype(float)
    # valid = close price present (matches the original "valid trades only" filter)
    trades = trades[trades["close_px"].notna() & (trades["open_px"] > 0)].copy()
    trades["is_win"] = trades["user_pnl_usd"] > 0
    trades["adverse_pct"] = (
        (trades["worst_adverse_px"] - trades["open_px"]).abs() / trades["open_px"] * 100.0
    )
    leverage = float(cfg.get("paper_leverage", 1000))
    buffer_bps = float(cfg.get("bust_buffer_bps", 5))
    tolerance = 1.0 / leverage - buffer_bps / 10_000.0   # fractional
    threshold_pct = tolerance * 100.0                    # in %
    return trades, threshold_pct


def liq_rates(trades: pd.DataFrame) -> dict:
    return {c: 100.0 * trades.loc[trades.coin == c, "paper_was_liquidated"].mean()
            for c in COINS}


# ---------------------------------------------------------------------------
# A — Paper vs HL liquidation rate
# ---------------------------------------------------------------------------
def chart_A(trades, out, liq):
    fig, ax = plt.subplots(figsize=(9, 6))
    x = np.arange(len(COINS))
    w = 0.38
    paper = [100.0 * trades.loc[trades.coin == c, "paper_was_liquidated"].mean() for c in COINS]
    hl = [100.0 * trades.loc[trades.coin == c, "hl_was_liquidated"].mean() for c in COINS]
    for i, c in enumerate(COINS):
        ax.bar(x[i] - w / 2, paper[i], w, color=COL[c],
               label="Paper 1000x (5 bps buffer)" if i == 0 else None)
        ax.bar(x[i] + w / 2, hl[i], w, color=COL[c], alpha=0.55, hatch="//",
               edgecolor="black", label="HL real-world (max-lev trades)" if i == 0 else None)
        ax.text(x[i] - w / 2, paper[i] + 1, f"{paper[i]:.2f}%", ha="center", fontweight="bold")
        ax.text(x[i] + w / 2, hl[i] + 1, f"{hl[i]:.2f}%", ha="center", color="#555")
    ax.set_xticks(x); ax.set_xticklabels(COINS, fontsize=13)
    ax.set_ylabel("Liquidation rate (%)")
    ax.set_title("BTC vs ETH — Paper liq rate vs HL liq rate\n"
                 "ETH Paper liq > BTC despite lower HL liq: ETH max-lev trades have larger adverse moves\n"
                 f"(canonical liq rates: BTC {liq['BTC']:.1f}% / ETH {liq['ETH']:.1f}%)",
                 fontsize=10)
    ax.legend(loc="upper left"); ax.grid(axis="y", alpha=0.3)
    ax.yaxis.set_major_formatter(matplotlib.ticker.PercentFormatter(decimals=0))
    _save(fig, out, "08b_coin_A_liq_rates.png")


# ---------------------------------------------------------------------------
# B — win rate by direction
# ---------------------------------------------------------------------------
def chart_B(trades, out, liq):
    fig, ax = plt.subplots(figsize=(9, 6))
    x = np.arange(len(COINS))
    w = 0.38
    for i, c in enumerate(COINS):
        sub = trades[trades.coin == c]
        wl = 100.0 * sub.loc[sub.direction == "long", "is_win"].mean()
        ws = 100.0 * sub.loc[sub.direction == "short", "is_win"].mean()
        ax.bar(x[i] - w / 2, wl, w, color=COL_LONG, label="Long" if i == 0 else None)
        ax.bar(x[i] + w / 2, ws, w, color=COL_SHORT, label="Short" if i == 0 else None)
        ax.text(x[i] - w / 2, wl + 0.1, f"{wl:.1f}%", ha="center")
        ax.text(x[i] + w / 2, ws + 0.1, f"{ws:.1f}%", ha="center")
    ax.set_xticks(x); ax.set_xticklabels(COINS, fontsize=13)
    ax.set_ylabel("Win rate (%)")
    ax.set_title("BTC vs ETH — Paper win rate by direction\n"
                 "(% of valid trades where trader ended positive after impact scaling)\n"
                 f"(canonical liq rates: BTC {liq['BTC']:.1f}% / ETH {liq['ETH']:.1f}%)",
                 fontsize=10)
    ax.legend(loc="upper right"); ax.grid(axis="y", alpha=0.3)
    ax.yaxis.set_major_formatter(matplotlib.ticker.PercentFormatter(decimals=0))
    _save(fig, out, "08b_coin_B_winrate.png")


# ---------------------------------------------------------------------------
# C — EV-per-trade distribution (trader perspective)
# ---------------------------------------------------------------------------
def chart_C(trades, out, liq):
    fig, ax = plt.subplots(figsize=(13, 6.5))
    vals = {c: signed_log10(trades.loc[trades.coin == c, "user_pnl_usd"].values) for c in COINS}
    lo = min(v.min() for v in vals.values())
    hi = max(v.max() for v in vals.values())
    bins = np.linspace(lo, hi, 80)
    for c in COINS:
        mean_ev = trades.loc[trades.coin == c, "user_pnl_usd"].mean()
        ax.hist(vals[c], bins=bins, density=True, alpha=0.5, color=COL[c],
                label=f"{c}  (mean EV = ${mean_ev:.1f})")
    ax.axvline(0, color="black", lw=1.2, label="EV = $0")
    ax.set_xlabel("signed log₁₀(|EV|+1)   ←  loss  |  win  →")
    ax.set_ylabel("Density")
    ax.set_title("BTC vs ETH — EV per trade distribution (trader perspective, Paper mechanics)\n"
                 "Left of zero = trader lost money; Right = trader won\n"
                 f"(canonical liq rates: BTC {liq['BTC']:.1f}% / ETH {liq['ETH']:.1f}%)",
                 fontsize=10)
    ax.legend(loc="upper right"); ax.grid(alpha=0.25)
    _save(fig, out, "08b_coin_C_ev_dist.png")


# ---------------------------------------------------------------------------
# D — worst adverse move distribution + bust threshold
# ---------------------------------------------------------------------------
def chart_D(trades, out, threshold_pct):
    fig, ax = plt.subplots(figsize=(13, 6.5))
    # Full (unfiltered) adverse-move array per coin — used for the "% above
    # threshold", which must equal the liquidation rate (trades with a zero /
    # missing adverse move are NOT liquidated and must stay in the denominator).
    adv_full = {c: trades.loc[trades.coin == c, "adverse_pct"].values for c in COINS}
    # Positive-only subset, used solely for the log-scale histogram.
    adv_pos = {c: v[(v > 0) & np.isfinite(v)] for c, v in adv_full.items()}
    logvals = {c: np.log10(v) for c, v in adv_pos.items()}
    lo = min(v.min() for v in logvals.values())
    hi = max(v.max() for v in logvals.values())
    bins = np.linspace(lo, hi, 90)
    for c in COINS:
        p50 = np.median(adv_pos[c])
        # "% above threshold" is the Paper liquidation rate itself — computed on
        # ALL valid trades (the histogram's positive filter must NOT shrink the
        # denominator), so it agrees with Figure 2 (80.0% / 91.5%).
        above = 100.0 * trades.loc[trades.coin == c, "paper_was_liquidated"].mean()
        ax.hist(logvals[c], bins=bins, density=True, alpha=0.5, color=COL[c],
                label=f"{c}  p50={p50:.3f}% → {above:.1f}% above threshold")
    ax.axvline(np.log10(threshold_pct), color="black", lw=2, ls="--",
               label=f"Paper bust threshold = {threshold_pct:.2f}% adverse move")
    total = len(trades)
    ax.set_xlabel("log₁₀(worst adverse move %)   [Paper liquidation threshold shown]")
    ax.set_ylabel("Density")
    ax.set_title("KEY CHART — worst adverse move distribution by coin "
                 f"(valid trades, n={total/1e6:.1f}M)\n"
                 "Area to RIGHT of threshold → Paper liquidation\n"
                 "ETH trades are structurally more volatile (larger adverse moves) "
                 "→ higher Paper liq despite lower HL liq", fontsize=10)
    ax.legend(loc="upper left"); ax.grid(alpha=0.25)
    _save(fig, out, "08b_coin_D_adverse_moves.png")


# ---------------------------------------------------------------------------
# E — LP delta per trade distribution
# ---------------------------------------------------------------------------
def chart_E(trades, out, liq):
    fig, ax = plt.subplots(figsize=(13, 6.5))
    vals = {c: signed_log10(trades.loc[trades.coin == c, "lp_balance_delta_usd"].values)
            for c in COINS}
    lo = min(v.min() for v in vals.values())
    hi = max(v.max() for v in vals.values())
    bins = np.linspace(lo, hi, 80)
    for c in COINS:
        mean_d = trades.loc[trades.coin == c, "lp_balance_delta_usd"].mean()
        ax.hist(vals[c], bins=bins, density=True, alpha=0.5, color=COL[c],
                label=f"{c}  (mean LP delta = ${mean_d:.2f})")
    ax.axvline(0, color="black", lw=1.2)
    ax.set_xlabel("signed log₁₀(|LP delta|+1)   ←  LP pays winner  |  LP gains from loser  →")
    ax.set_ylabel("Density")
    ax.set_title("BTC vs ETH — LP delta per trade distribution\n"
                 "Right side: LP gains from losers/liquidations | Left side: LP pays winners (impact-adjusted)\n"
                 f"(canonical liq rates: BTC {liq['BTC']:.1f}% / ETH {liq['ETH']:.1f}%)",
                 fontsize=10)
    ax.legend(loc="upper right"); ax.grid(alpha=0.25)
    _save(fig, out, "08b_coin_E_lp_delta.png")


# ---------------------------------------------------------------------------
# F — summary table
# ---------------------------------------------------------------------------
def chart_F(trades, out, liq):
    cols = ["Coin", "n trades", "HL max-lev", "Paper liq", "HL liq",
            "Paper liq L/S", "Win rate L/S", "EV/trade ($)", "LP Δ avg ($)", "Long/Short"]
    rows = []
    cell_colours = []
    for c in COINS:
        sub = trades[trades.coin == c]
        paper_liq = 100.0 * sub["paper_was_liquidated"].mean()
        hl_liq = 100.0 * sub["hl_was_liquidated"].mean()
        pl = 100.0 * sub.loc[sub.direction == "long", "paper_was_liquidated"].mean()
        ps = 100.0 * sub.loc[sub.direction == "short", "paper_was_liquidated"].mean()
        wl = 100.0 * sub.loc[sub.direction == "long", "is_win"].mean()
        ws = 100.0 * sub.loc[sub.direction == "short", "is_win"].mean()
        ev = sub["user_pnl_usd"].mean()
        lpd = sub["lp_balance_delta_usd"].mean()
        n_long = 100.0 * (sub.direction == "long").mean()
        rows.append([
            c, f"{len(sub):,}", f"{MAX_LEV[c]}x",
            f"{paper_liq:.2f}%", f"{hl_liq:.2f}%",
            f"L {pl:.1f}% / S {ps:.1f}%", f"L {wl:.1f}% / S {ws:.1f}%",
            f"${ev:.2f}", f"${lpd:.3f}", f"{n_long:.0f}% / {100 - n_long:.0f}%",
        ])
        base = COL[c]
        colours = ["#fff3e0" if c == "BTC" else "#e8eaf6"] + ["white"] * 2 + \
                  ["#fcd9a8", "#d7ead3"] + ["white"] * 5
        cell_colours.append(colours)

    fig, ax = plt.subplots(figsize=(15, 3))
    ax.axis("off")
    tbl = ax.table(cellText=rows, colLabels=cols, cellColours=cell_colours,
                   colColours=["#c5cfe0"] * len(cols), loc="center", cellLoc="center")
    tbl.auto_set_font_size(False); tbl.set_fontsize(10); tbl.scale(1, 2.2)
    ax.set_title("BTC vs ETH — Summary table  (valid trades only, Paper 1000x 5bps)\n"
                 f"(canonical liq rates: BTC {liq['BTC']:.1f}% / ETH {liq['ETH']:.1f}%)",
                 fontsize=11, fontweight="bold")
    _save(fig, out, "08b_coin_F_summary.png")


# ---------------------------------------------------------------------------
# 08c — daily Paper liquidation rate per coin (time series)
# ---------------------------------------------------------------------------
def chart_liq_by_coin(trades, out, liq):
    t = trades.copy()
    t["day"] = pd.to_datetime((t["close_time_ms"] // DAY_MS) * DAY_MS, unit="ms", utc=True)
    adl_days = sorted(t.loc[t.get("hl_was_adl", False) == True, "day"].unique()) \
        if "hl_was_adl" in t.columns else []

    fig, axes = plt.subplots(2, 1, figsize=(15, 9), sharex=True)
    for ax, c in zip(axes, COINS):
        sub = t[t.coin == c]
        daily = sub.groupby("day")["paper_was_liquidated"].mean() * 100.0
        ax.plot(daily.index, daily.values, color=COL[c], lw=1.5)
        ax.fill_between(daily.index, 0, daily.values, color=COL[c], alpha=0.12)
        avg = liq[c]
        ax.axhline(avg, color=COL[c], ls=":", lw=1)
        ax.text(daily.index[-1], avg, f" avg {avg:.1f}%", color=COL[c],
                va="center", fontsize=9)
        for d in adl_days:
            ax.axvspan(d, d + pd.Timedelta(days=1), color="#7b5ea8", alpha=0.18)
        ax.set_ylim(0, 105); ax.set_ylabel("% trades liquidated in Paper")
        ax.set_title(f"Daily Paper liquidation rate — {c}  "
                     f"(max lev: {MAX_LEV[c]}x, Paper 1000x, 5 bps buffer)", fontsize=12)
        ax.grid(alpha=0.25)
    axes[-1].xaxis.set_major_formatter(mdates.DateFormatter("%b %y"))
    fig.autofmt_xdate()
    _save(fig, out, "08c_liq_by_coin.png")


# ---------------------------------------------------------------------------
# Figure 4 — share of a winning trade kept after impact (deployed params)
# ---------------------------------------------------------------------------
def _scale(p, move):
    return ((1.0 - p["base_rate"]) /
            (1.0 + 1.0 / (move * p["rate_multiplier"])
             + p["reference_notional_usd"] / (move * p["position_multiplier"])))


def _retained(p, move, deadband):
    """Share of the raw win the trader keeps: impact scale on the deadband-net
    move, times the fraction of the move that survives the deadband."""
    net = move - deadband
    if net <= 0.0:
        return 0.0
    return _scale(p, net) * (net / move)


def chart_impact_curve(cfg, out, threshold_pct):
    imp = cfg["impact"]
    deadband = cfg.get("deadband_bps", 0.0) / 10_000.0
    moves = np.logspace(np.log10(1e-5), np.log10(0.20), 800)   # 0.001% → 20%
    fig, ax = plt.subplots(figsize=(11, 6.5))
    for c in COINS:
        y = np.array([_retained(imp[c], m, deadband) for m in moves]) * 100.0
        ax.plot(moves * 100.0, y, color=COL[c], lw=2.3, label=c)
    # anchor points computed directly from the deployed formula (with deadband)
    for mv in (0.0001, 0.001, 0.01, 0.05):
        for c in COINS:
            s = _retained(imp[c], mv, deadband) * 100.0
            ax.plot(mv * 100.0, s, "o", color=COL[c], ms=5, zorder=5)
            ax.annotate(f"{s:.1f}%", (mv * 100.0, s), textcoords="offset points",
                        xytext=(5, 5 if c == "BTC" else -12), fontsize=8,
                        color=COL[c], fontweight="bold")
    ax.axvline(deadband * 100.0, color="black", lw=1.5, ls="--",
               label=f"deadband ({cfg.get('deadband_bps', 0):.1f} bps = half CLOB spread)")
    ax.set_xscale("log")
    ax.set_xlim(0.001, 20.0)
    ax.set_ylim(0, 95)
    ax.xaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(
        lambda v, _: f"{v:g}%"))
    ax.yaxis.set_major_formatter(matplotlib.ticker.PercentFormatter(decimals=0))
    ax.set_xlabel("Winning price move (%, log scale)")
    ax.set_ylabel("Share of raw gain the trader keeps")
    ax.set_title("Share of a winning trade kept after asymmetric impact + deadband\n"
                 f"base_rate {imp['BTC']['base_rate']:.0%}, rate_mult {imp['BTC']['rate_multiplier']:.0f}, "
                 f"ref ${imp['BTC']['reference_notional_usd']/1000:.0f}K, "
                 f"posMult BTC {imp['BTC']['position_multiplier']/1e6:,.3f}M / "
                 f"ETH {imp['ETH']['position_multiplier']/1e6:,.3f}M — 0 below the deadband",
                 fontsize=10)
    ax.legend(loc="best", framealpha=0.9)
    ax.grid(alpha=0.25, which="both")
    _save(fig, out, "08d_impact_curve.png")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    base = Path(__file__).resolve().parent
    p.add_argument("--sim-dir", type=Path, default=base / "sim_flow_1.00")
    p.add_argument("--config", type=Path, default=base / "paper_config.yaml")
    p.add_argument("--charts-dir", type=Path, default=base / "charts")
    args = p.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    with open(args.config) as f:
        cfg = yaml.safe_load(f)
    args.charts_dir.mkdir(parents=True, exist_ok=True)

    trades, threshold_pct = load(args.sim_dir, cfg)
    liq = liq_rates(trades)
    logging.info("Per-coin charts from %s (%s trades, liq BTC %.1f%% / ETH %.1f%%):",
                 args.sim_dir.name, f"{len(trades):,}", liq["BTC"], liq["ETH"])

    chart_A(trades, args.charts_dir, liq)
    chart_B(trades, args.charts_dir, liq)
    chart_C(trades, args.charts_dir, liq)
    chart_D(trades, args.charts_dir, threshold_pct)
    chart_E(trades, args.charts_dir, liq)
    chart_F(trades, args.charts_dir, liq)
    chart_liq_by_coin(trades, args.charts_dir, liq)
    chart_impact_curve(cfg, args.charts_dir, threshold_pct)
    logging.info("Done → %s/", args.charts_dir)


if __name__ == "__main__":
    main()
